### ISSUE TITLE
Prepare v1 of application storage format (what data should be stored in user's browser storage). Refer to list of promised functionalities.

### ISSUE THREAD

**Issue by osiewicz** [halflajf/YASP#1]

**Comment by emqi** [comment]
Here's what I propose:
`{
	"title": "Note title",
	"content": "Note content",
	"tags": ["Array", "of", "tags", "we", "can", "group", "notes", "by"],
	"whenCreated": "Date of creation",
	"whenEdited": "Date of last edit"
}`

**Comment by emqi** [comment]
Here's what I propose:

{
"title": "Note title",
"content": "Note content",
"tags": ["Array", "of", "tags", "we", "can", "group", "notes", "by"],
"whenCreated": "Date of creation",
"whenEdited": "Date of last edit"
}
